"""Remove username column from messages

Revision ID: 61d5d5a52651
Revises: ce6efb09cc23
Create Date: 2025-02-25 14:40:04.308910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61d5d5a52651'
down_revision = 'ce6efb09cc23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint('messages_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('username')

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.alter_column('creator_id',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.alter_column('creator_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('messages_user_id_fkey', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
