"""update user e message

Revision ID: a989dd75333f
Revises: 61d5d5a52651
Create Date: 2025-02-25 14:57:39.692624

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a989dd75333f'
down_revision = '61d5d5a52651'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        # 1. Adiciona a coluna user_id como nullable
        batch_op.add_column(sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True))

    # 2. Preenche user_id com um valor padrão (ex: ID do usuário administrador)
    # Substitua 'd8f1a8b6-e2df-4945-afbc-3ad7fbd3d315' pelo ID de um usuário válido
    op.execute("""
        UPDATE messages
        SET user_id = '2eb20d15-1e6b-4326-90b1-85386b2d9b5a'
        WHERE user_id IS NULL;
    """)

    # 3. Altera a coluna user_id para NOT NULL
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('user_id', nullable=False)

    # 4. Cria a chave estrangeira para a tabela users
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_messages_user_id', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        # 1. Remove a restrição NOT NULL
        batch_op.alter_column('user_id', nullable=True)

        # 2. Remove a chave estrangeira
        batch_op.drop_constraint('fk_messages_user_id', type_='foreignkey')

        # 3. Remove a coluna user_id
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###

# """update user e message

# Revision ID: a989dd75333f
# Revises: 61d5d5a52651
# Create Date: 2025-02-25 14:57:39.692624

# """
# from alembic import op
# import sqlalchemy as sa


# # revision identifiers, used by Alembic.
# revision = 'a989dd75333f'
# down_revision = '61d5d5a52651'
# branch_labels = None
# depends_on = None


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('messages', schema=None) as batch_op:
        
#         batch_op.add_column(sa.Column('user_id', sa.UUID(), nullable=False))
        
#         batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

#     # ### end Alembic commands ###


# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('messages', schema=None) as batch_op:
#         batch_op.drop_constraint(None, type_='foreignkey')
#         batch_op.drop_column('user_id')

#     # ### end Alembic commands ###
