"""Descrição da migração

Revision ID: ce6efb09cc23
Revises: 63336a8efee4
Create Date: 2025-02-24 10:13:04.913093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce6efb09cc23'
down_revision = '63336a8efee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blacklist_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_blacklist_tokens_id')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('ix_messages_id')

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.UUID(), nullable=True))
        batch_op.drop_index('ix_rooms_id')
        batch_op.create_foreign_key(None, 'users', ['creator_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_id', ['id'], unique=False)

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('ix_rooms_id', ['id'], unique=False)
        batch_op.drop_column('creator_id')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('ix_messages_id', ['id'], unique=False)

    with op.batch_alter_table('blacklist_tokens', schema=None) as batch_op:
        batch_op.create_index('ix_blacklist_tokens_id', ['id'], unique=False)

    # ### end Alembic commands ###
